### ISSUE TITLE
Inventory bug and player bug

### ISSUE THREAD

**Issue by xanderc5** [mobends/MoBends#2]
First off, the inventory items won't show up. The inventory is completely blank. Even though you can see your items in the hotbar, they won't show up in the inventory and the rest of the items too. No tooltip too, but you can still grab the items and switch them around.

Second bug, your arm and head just stays one meter up in the sky, and the armour and item your holding glitches out of place in the player. If you look at a specific angle, the bug will dissapear, but once you look back or do something the bug will appear again.

**Comment by iwoplaza** [comment]
The bug with the arm and head displacement should no longer be present in the upcoming release :).
As for the inventory bug, could I get a screenshot?

**Comment by SpinoLeSs** [comment]
This problem also occurs for me.
![2018-07-02_15 21 20](https://user-images.githubusercontent.com/40765010/42166611-d852cc8a-7e0b-11e8-903e-4e2c8d97a493.png)

**Comment by xanderc5** [comment]
Sorry for the late reply, but that's exactly what the inventory bug looks like. 

Yeah.. not much more to say than good luck with fixing the bug! 👍 😃

**Comment by iwoplaza** [comment]
I've rewritten the system, which is going to ship with the upcoming 1.0.0 update. It doesn't occur there, and it has no reason to, so stay tuned for that! 😄
