### ISSUE TITLE
Mod Compatibility Issue 

### ISSUE THREAD

**Issue by Adarcer** [mobends/MoBends#3]
Not sure what would cause this but try Mo bends with Construct's Armory and as long as your mod is enabled to work with player the armor renders all over the place too hilarious results, for the moment I have been using cosmetic armor too hide the other armor.. 

(https://minecraft.curseforge.com/projects/constructs-armory)

**Comment by iwoplaza** [comment]
It has been added to my to-do list ;).

**Comment by CheshireSwift** [comment]
Any progress on this?

**Comment by iwoplaza** [comment]
According to my testers, this is the current state of compatibility between the two mods 🙂.

![image](https://user-images.githubusercontent.com/7166752/51442754-4658fd80-1ce0-11e9-830b-ad6186018257.png)
![image](https://user-images.githubusercontent.com/7166752/51442757-4e18a200-1ce0-11e9-8c34-9b567d6cee8e.png)
![image](https://user-images.githubusercontent.com/7166752/51442763-57097380-1ce0-11e9-92a5-afc56d652724.png)

Right now I'm working on improving a few different areas of the mod, but when I release the public beta I'll try to get in touch with developers of those kinds of mods, and try to whip up some cross-compatibility in both of our codebases 😄.

**Comment by Ye-Old-Apple** [comment]
any more progress or updates?

**Comment by iwoplaza** [comment]
I'm trying to merge all Construct's Armory reports into one, let's continue our discussion here #196.
